name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Cable Color Converter
        package.name = cablecolorconverter
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 0.1
        requirements = python3,kivy

        [buildozer]
        log_level = 2

        [android]
        api = 33
        minapi = 21
        ndk = 25b
        accept_sdk_license = True
        EOF

    - name: Build APK with Buildozer Docker
      run: |
        docker run --rm -v "$PWD":/home/user/hostcwd \
          kivy/buildozer:latest \
          bash -c "cd /home/user/hostcwd && buildozer android debug"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
